<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>TFusion.Diagnostics</AssemblyName>
    <RootNamespace>TFusion.Diagnostics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TFusion.Foundation\TFusion.Foundation.csproj" />
    <ProjectReference Include="..\TFusion.Kernel.Interop\TFusion.Kernel.Interop.csproj" />
  </ItemGroup>
</Project>
